# -*- coding: utf-8 -*-
"""Assigment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RzZho8QpbN7oqEY-rKr7DPRcm7jdZm0Y

### Importing Important Libraries
"""

import pandas as pd # import panda library as pd for data manipulation
import matplotlib.pyplot as plt # import matplotlib as plt for data visualitzation
from matplotlib import style
import numpy as np # import nump as np
import seaborn as sns # seaborn is data visualization library build on matplotlib
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

"""### Implement a Function Which return Original DataFrame, Transposed DataFrames"""

def transpose_file(filename: str):

    # Read the file into a pandas dataframe
    dataframe = pd.read_csv(filename)

    # Transpose the dataframe
    df_transposed = dataframe.transpose()

    # Populate the header of the transposed dataframe with the header information

    # silice the dataframe to get the year as columns
    df_transposed.columns = df_transposed.iloc[1]

    # As year is now columns so we don't need it as rows
    transposed_year = df_transposed[0:].drop('year')

    # silice the dataframe to get the country as columns
    df_transposed.columns = df_transposed.iloc[0]

    # As country is now columns so we don't need it as rows
    transposed_country = df_transposed[0:].drop('country')

    return dataframe, transposed_country, transposed_year

# Passing filename to Real Worldbank data function
# will return three dataframe:
# org dataframe, transposed country as columns and transposed year as column

org_df, df_by_country, df_by_year = transpose_file('/content/worldbank_dataset.csv')

"""### Original DataFrame"""

# show the first 5 row
org_df.head(5)

"""### show the statistics of Original Data"""

org_df.describe() #describe method show the statistic of dataframe

"""### DataFrame In Which Countries are Columns"""

# show the first 5 row
df_by_country.head(5)

"""### DataFrame In Which Year are Columns"""

# show the first 5 row
df_by_year

org_df.columns

"""### Create DataFrame related to nitrous_oxide
### For All the countries and years
"""

# we want to see countries nitrous_oxide over specfic years
# we need to filter our original data frame to get specific fields

# Filter the data for non-null values
nitrous_oxide = org_df[['country', 'year', 'nitrous_oxide']].dropna()

"""### Get Data to Specific Years from 1990 to 2020"""

import random

# Define the years for which you want to plot data
years_to_plot = [1990, 2000, 2010, 2015]

# Get a list of all named colors in Matplotlib
all_colors = list(mcolors.CSS4_COLORS.keys())

# Select a specific number of random colors from the list
num_colors_to_select = 20  # You can change this number as needed
selected_colors = random.sample(all_colors, num_colors_to_select)

countries = nitrous_oxide.country.unique()
countries

"""### Plot Barplot"""

# Create a figure and set its size
plt.figure(figsize=(15, 10))

# Set width of bars
barWidth = 0.1

for i, year in enumerate(years_to_plot):
    data = nitrous_oxide[nitrous_oxide['year'] == year]
    plt.bar(np.arange(data.shape[0]) + (0.2 * i), data['nitrous_oxide'], color=selected_colors[i], width=barWidth, label=str(year))

# Show legends, labels, and title
plt.legend()
plt.xlabel('Country', fontsize=15)
plt.title("Nitrous Oxide", fontsize=15)

# Add country names to the x-axis ticks
plt.xticks(np.arange(len(countries)) + 0.2, countries, fontsize=10, rotation=45)

# Show the plot
plt.show()

org_df.columns

"""### Get data of agricultural_land over the years"""

# we want to see countries agricultural_land over specfic years
# we need to filter our original data frame to get specific fields

# Filter the data for non-null values
agricultural_land = org_df[['country', 'year', 'agricultural_land']].dropna()

"""### Filter from specific year from 1990 to 2020"""

import random

# Define the years for which you want to plot data
years_to_plot = [1990, 2000, 2010, 2015, 2020]

# Get a list of all named colors in Matplotlib
all_colors = list(mcolors.CSS4_COLORS.keys())

# Select a specific number of random colors from the list
num_colors_to_select = 10  # You can change this number as needed
selected_colors = random.sample(all_colors, num_colors_to_select)

countries = agricultural_land.country.unique()

"""### PLOT barplot"""

# Create a figure and set its size
plt.figure(figsize=(15, 10))

# Set width of bars
barWidth = 0.1

for i, year in enumerate(years_to_plot):
    data = agricultural_land[agricultural_land['year'] == year]
    plt.bar(np.arange(data.shape[0]) + (0.2 * i), data['agricultural_land'], color=selected_colors[i], width=barWidth, label=str(year))

# Show legends, labels, and title
plt.legend()
plt.xlabel('Country', fontsize=15)
plt.title("Agricultural Land", fontsize=15)

# Add country names to the x-axis ticks
plt.xticks(np.arange(len(countries)) + 0.2, countries, fontsize=10, rotation=45)

# Show the plot
plt.show()

org_df.country.unique()

"""### Making a DataFrame related to Uruguay"""

# making dataframe of Uruguay data from the original dataframe
urg = org_df[org_df['country'] == 'Uruguay']

"""### Implement a Function which removes Null values and return clean data"""

def remove_null_values(feature):
    return np.array(feature.dropna())

"""### For the Features Present In Uruguay DataFrame remove the null values
### Print Each Features Size
"""

org_df.columns

# List of columns to extract
columns_of_interest = ['nitrous_oxide', 'agricultural_land',
       'greenhouse_gas_emissions', 'population_growth', 'GDP',
       'renewable_electricity', 'total_population', 'forest_area',
       'alternative_energy', 'expenses']

# Dictionary to store feature data after removing null values
feature_data = {}

# Loop through each column to extract and clean the data
for column in columns_of_interest:
    feature_data[column] = remove_null_values(urg[[column]])
    print(f'{column} Length = {len(feature_data[column])}')

# Create data_sources dictionary dynamically
data_sources = {column: feature_data[column] for column in columns_of_interest}

# Determine the number of rows to include
num_rows = 26

# Create the DataFrame using dictionary comprehension
urg_clean_data = pd.DataFrame({
    key: [data_sources[key][x][0] for x in range(num_rows)] for key in data_sources
})

import seaborn as sns
import matplotlib.pyplot as plt

# Create a correlation matrix
correlation_matrix = urg_clean_data.corr()

# Create a heatmap using Seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='YlGnBu', fmt=".2f")
plt.title('Correlation Heatmap for Uruguay')
plt.show()

correlation_matrix

org_df.country.unique()

"""### Making a DataFrame related to Paraguay"""

# making dataframe of Paraguay data from the original dataframe
par = org_df[org_df['country'] == 'Paraguay']

"""### For the Features Present In DataFrame remove the null values
### Print Each Features Size
"""

par.columns

# List of columns to extract
columns_of_interest = ['nitrous_oxide', 'agricultural_land',
       'greenhouse_gas_emissions', 'population_growth', 'GDP',
       'renewable_electricity', 'total_population', 'forest_area',
       'alternative_energy',
       ]

# Dictionary to store feature data after removing null values
feature_data = {}

# Loop through each column to extract and clean the data
for column in columns_of_interest:
    feature_data[column] = remove_null_values(par[[column]])
    print(f'{column} Length = {len(feature_data[column])}')

# Create data_sources dictionary dynamically
data_sources = {column: feature_data[column] for column in columns_of_interest}

# Determine the number of rows to include
num_rows = 26

# Create the DataFrame using dictionary comprehension
par_clean_data = pd.DataFrame({
    key: [data_sources[key][x][0] for x in range(num_rows)] for key in data_sources
})

# Create a correlation matrix
correlation_matrix = par_clean_data.corr()

# Create a heatmap using Seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='Blues', fmt=".2f")
plt.title('Correlation Heatmap for Paraguay')
plt.show()

correlation_matrix

org_df.country.unique()

"""### Making a DataFrame related to Costa Rica"""

# making dataframe of Costa Rica data from the original dataframe
cr = org_df[org_df['country'] == 'Costa Rica']

"""### For the Features Present In DataFrame remove the null values
### Print Each Features Size
"""

cr.columns

# List of columns to extract
columns_of_interest = [ 'nitrous_oxide', 'agricultural_land',
       'greenhouse_gas_emissions', 'population_growth', 'GDP',
       'renewable_electricity', 'total_population', 'forest_area',
       'alternative_energy', 'expenses']

# Dictionary to store feature data after removing null values
feature_data = {}

# Loop through each column to extract and clean the data
for column in columns_of_interest:
    feature_data[column] = remove_null_values(cr[[column]])
    print(f'{column} Length = {len(feature_data[column])}')

# Create data_sources dictionary dynamically
data_sources = {column: feature_data[column] for column in columns_of_interest}

# Determine the number of rows to include
num_rows = 26

# Create the DataFrame using dictionary comprehension
cr_clean_data = pd.DataFrame({
    key: [data_sources[key][x][0] for x in range(num_rows)] for key in data_sources
})

import seaborn as sns
import matplotlib.pyplot as plt

# Create a correlation matrix
correlation_matrix = cr_clean_data.corr()

# Create a heatmap using Seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='Greens', fmt=".2f")
plt.title('Correlation Heatmap for Costa Rica')
plt.show()

correlation_matrix

org_df.columns

"""### Get the Year, Country Data Related to greenhouse_gas_emissions"""

# we want to see countries greenhouse_gas_emissions over the years
# we need to filter our original data frame to get specific fields
greenhouse_gas_emissions = org_df[['country','year','greenhouse_gas_emissions']]

# drop the null values present in the dataset
greenhouse_gas_emissions  = greenhouse_gas_emissions.dropna()

"""### Filter the Data For All the Countries"""

# Define countries of interest
countries = org_df.country.unique()
countries

"""### Line Plot of greenhouse_gas_emissions"""

# Set fig size
plt.figure(figsize=(15, 10))

# Loop through countries and plot population_growth over the years
for country in countries:
    country_data = greenhouse_gas_emissions[greenhouse_gas_emissions['country'] == country]
    plt.plot(country_data['year'], country_data['greenhouse_gas_emissions'], label=country)

# Set X-axis label and title
plt.xlabel('Year', fontweight='bold')
plt.title("Greenhouse Gas Emissions")

# Show legends and plot
plt.legend(bbox_to_anchor=(0.89, 0.7), shadow=True)
plt.show()

"""### Get the Year, Country Data Related to forest_area"""

# we want to see countries forest_area over the years
# we need to filter our original data frame to get specific fields
forest_area = org_df[['country','year','forest_area']]

# drop the null values present in the dataset
forest_area  = forest_area.dropna()

"""### Filter the Data For All the Countries"""

# Define countries of interest
countries = org_df.country.unique()
countries

"""### Line Plot of forest_area"""

# Set fig size
plt.figure(figsize=(15, 10))

# Loop through countries and plot forest_area over the years
for country in countries:
    country_data = forest_area[forest_area['country'] == country]
    plt.plot(country_data['year'], country_data['forest_area'], label=country)

# Set X-axis label and title
plt.xlabel('Year', fontweight='bold')
plt.title("Forest Area")

# Show legends and plot
plt.legend(bbox_to_anchor=(0.89, 0.7), shadow=True)
plt.show()

org_df.columns

# we want to see countries GDP over the years
renewable_electricity = org_df[['country','year','renewable_electricity']]

# drop the null values present in the dataset
renewable_electricity = renewable_electricity.dropna()

### Filter from specific year from 1990 to 2015
# filter data related to 1990
renewable_electricity_1990 = renewable_electricity[renewable_electricity['year'] == 1990]

# filter data related to 2010
renewable_electricity_2010 = renewable_electricity[renewable_electricity['year'] == 2010]

# filter data related to 2020
renewable_electricity_2020 = renewable_electricity[renewable_electricity['year'] == 2020]

renewable_electricity_1990

renewable_electricity_2010